In [3]:
%pip install kedro-datasets[pandas]

Requirement already satisfied: kedro-datasets[pandas] in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (9.6.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: kedro<2.0.0,>=1.0.0rc1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro-datasets[pandas]) (1.7.0)
Requirement already satisfied: lazy_loader in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro-datasets[pandas]) (0.6)
Requirement already satisfied: attrs>=21.3 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (26.1.0)
Requirement already satisfied: build>=0.7.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (1.6.1)
Requirement already satisfied: click>=8.2 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (8.5.0)
Requirement already satisfied: cookiecutter<3.0,>=2.1.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (2.7.1)
Requirement already satisfied: dynaconf<4.0,>=3.1.2 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (3.3.5)
Requirement already satisfied: fsspec>=2021.4 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (2026.9.0)
Requirement already satisfied: gitpython>=3.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (3.2.1)
Requirement already satisfied: kedro-telemetry>=0.5.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (0.9.0)
Requirement already satisfied: more_itertools>=8.14.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (11.2.1)
Requirement already satisfied: omegaconf>=2.1.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (2.4.0)
Requirement already satisfied: parse>=1.19.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (1.22.3)
Requirement already satisfied: pluggy>=1.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (1.7.0)
Requirement already satisfied: PyYAML<7.0,>=4.2 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (6.0.3)
Requirement already satisfied: rich<16.0,>=12.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (15.0.0)
Requirement already satisfied: tomli-w in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (1.2.0)
Requirement already satisfied: typing_extensions>=4.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (4.16.0)
Requirement already satisfied: binaryornot>=0.4.4 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (0.6.0)
Requirement already satisfied: Jinja2<4.0.0,>=2.7 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (3.1.6)
Requirement already satisfied: python-slugify>=4.0.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (9.1.3)
Requirement already satisfied: requests>=2.23.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (2.34.2)
Requirement already satisfied: arrow in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (1.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from Jinja2<4.0.0,>=2.7->cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (3.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from rich<16.0,>=12.0->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from rich<16.0,>=12.0->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (2.21.0)
Requirement already satisfied: packaging>=24.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from build>=0.7.0->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (26.3)
Requirement already satisfied: pyproject_hooks in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from build>=0.7.0->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (1.3.3)
Requirement already satisfied: colorama in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from build>=0.7.0->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from gitpython>=3.0->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython>=3.0->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (5.0.3)
Requirement already satisfied: appdirs>=1.4.4 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro-telemetry>=0.5.0->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (1.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from requests>=2.23.0->cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from requests>=2.23.0->cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from requests>=2.23.0->cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from requests>=2.23.0->cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (2026.10.18)
Requirement already satisfied: mdurl~=0.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich<16.0,>=12.0->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (0.1.2)
Requirement already satisfied: text-unidecode>=1.3 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from python-slugify>=4.0.0->cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (1.3)
Requirement already satisfied: python-dateutil>=2.7.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from arrow->cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from arrow->cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from python-dateutil>=2.7.0->arrow->cookiecutter<3.0,>=2.1.1->kedro<2.0.0,>=1.0.0rc1->kedro-datasets[pandas]) (1.17.0)
Requirement already satisfied: deltalake>=0.10.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro-datasets[pandas]) (1.6.6)
Requirement already satisfied: openpyxl<4.0,>=3.0.6 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro-datasets[pandas]) (3.1.5)
Requirement already satisfied: pandas-gbq>=0.12.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro-datasets[pandas]) (0.35.2)
Requirement already satisfied: tables>=3.6 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro-datasets[pandas]) (3.11.1)
Requirement already satisfied: pyarrow>=6.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro-datasets[pandas]) (26.0.0)
Requirement already satisfied: SQLAlchemy<3.0,>=1.4 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro-datasets[pandas]) (2.1.5)
Requirement already satisfied: pyodbc>=4.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro-datasets[pandas]) (5.3.0)
Requirement already satisfied: lxml<7.0,>=6.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from kedro-datasets[pandas]) (6.1.3)
Requirement already satisfied: et-xmlfile in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from openpyxl<4.0,>=3.0.6->kedro-datasets[pandas]) (2.0.0)
Requirement already satisfied: arro3-core>=0.5.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from deltalake>=0.10.0->kedro-datasets[pandas]) (0.9.1)
Requirement already satisfied: deprecated>=1.2.18 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from deltalake>=0.10.0->kedro-datasets[pandas]) (3.0.0)
Requirement already satisfied: wrapt<3,>=1.16 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from deprecated>=1.2.18->deltalake>=0.10.0->kedro-datasets[pandas]) (2.5.1)
Requirement already satisfied: setuptools in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from pandas-gbq>=0.12.0->kedro-datasets[pandas]) (84.0.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.1.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from pandas-gbq>=0.12.0->kedro-datasets[pandas]) (1.8.0)
Requirement already satisfied: numpy>=1.26.4 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from pandas-gbq>=0.12.0->kedro-datasets[pandas]) (2.5.4)
Requirement already satisfied: pandas>=1.5.3 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from pandas-gbq>=0.12.0->kedro-datasets[pandas]) (3.0.6)
Requirement already satisfied: pydata-google-auth>=1.5.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from pandas-gbq>=0.12.0->kedro-datasets[pandas]) (1.9.1)
Requirement already satisfied: psutil>=5.9.8 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from pandas-gbq>=0.12.0->kedro-datasets[pandas]) (7.2.2)
Requirement already satisfied: google-api-core<3.0.0,>=2.25.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from pandas-gbq>=0.12.0->kedro-datasets[pandas]) (2.42.0)
Requirement already satisfied: google-auth>=2.14.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from pandas-gbq>=0.12.0->kedro-datasets[pandas]) (2.62.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from pandas-gbq>=0.12.0->kedro-datasets[pandas]) (1.5.0)
Requirement already satisfied: google-cloud-bigquery<4.0.0,>=3.20.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from pandas-gbq>=0.12.0->kedro-datasets[pandas]) (3.46.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.69.2 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from google-api-core<3.0.0,>=2.25.0->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (1.75.5)
Requirement already satisfied: protobuf<8.0.0,>=6.33.5 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from google-api-core<3.0.0,>=2.25.0->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (7.36.2)
Requirement already satisfied: proto-plus<2.0.0,>=1.26.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from google-api-core<3.0.0,>=2.25.0->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (1.29.0)
Requirement already satisfied: opentelemetry-api<2.0.0,>=1.44.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from google-api-core<3.0.0,>=2.25.0->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (1.45.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from google-auth>=2.14.1->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (0.4.2)
Requirement already satisfied: cryptography>=41.0.5 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from google-auth>=2.14.1->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (50.0.2)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (2.8.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (2.11.0)
Requirement already satisfied: grpcio<2.0.0,>=1.59.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (1.84.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.59.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (1.84.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery<4.0.0,>=3.20.0->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (1.9.0)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from cryptography>=41.0.5->google-auth>=2.14.1->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (2.1.1)
Requirement already satisfied: pycparser in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from cffi>=2.0.0->cryptography>=41.0.5->google-auth>=2.14.1->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (3.11)
Requirement already satisfied: requests-oauthlib>=0.7.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (2.0.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.14.1->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (0.6.4)
Requirement already satisfied: oauthlib>=3.0.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq>=0.12.0->kedro-datasets[pandas]) (4.0.0)
Requirement already satisfied: numexpr>=2.6.2 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from tables>=3.6->kedro-datasets[pandas]) (2.14.2)
Requirement already satisfied: py-cpuinfo in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from tables>=3.6->kedro-datasets[pandas]) (9.0.0)
Requirement already satisfied: blosc2>=2.3.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from tables>=3.6->kedro-datasets[pandas]) (4.14.1)
Requirement already satisfied: ndindex in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from blosc2>=2.3.0->tables>=3.6->kedro-datasets[pandas]) (1.10.1)
Requirement already satisfied: msgpack in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from blosc2>=2.3.0->tables>=3.6->kedro-datasets[pandas]) (1.2.3)
Requirement already satisfied: pydantic in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from blosc2>=2.3.0->tables>=3.6->kedro-datasets[pandas]) (2.14.1)
Requirement already satisfied: httpx[http2] in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from blosc2>=2.3.0->tables>=3.6->kedro-datasets[pandas]) (0.28.1)
Requirement already satisfied: threadpoolctl in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from blosc2>=2.3.0->tables>=3.6->kedro-datasets[pandas]) (3.7.0)
Requirement already satisfied: anyio in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from httpx[http2]->blosc2>=2.3.0->tables>=3.6->kedro-datasets[pandas]) (4.15.1)
Requirement already satisfied: httpcore==1.* in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from httpx[http2]->blosc2>=2.3.0->tables>=3.6->kedro-datasets[pandas]) (1.0.9)
Requirement already satisfied: h2<5,>=3 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from httpx[http2]->blosc2>=2.3.0->tables>=3.6->kedro-datasets[pandas]) (4.4.1)
Requirement already satisfied: hyperframe<7,>=6.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from h2<5,>=3->httpx[http2]->blosc2>=2.3.0->tables>=3.6->kedro-datasets[pandas]) (6.1.0)

In [4]:
%load_ext kedro.ipython

[10/19/26 16:47:56] INFO     Using                                                                  ]8;id=10301044;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=10301045;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\framework\project\__init__.py#347\347]8;;\
                             'C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.ve
                             nv\Lib\site-packages\kedro\framework\project\rich_logging.yml' as
                             logging configuration.

[10/19/26 16:47:57] INFO     Registered line magic '%reload_kedro'                                   ]8;id=10301052;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=10301053;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py#70\70]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=10301059;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=10301060;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py#72\72]8;;\

                    INFO     Resolved project path as:                                              ]8;id=10301066;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=10301067;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py#261\261]8;;\
                             C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\spac
                             eflights.
                             To set a different path, run '%reload_kedro <project_root>'

[10/19/26 16:47:57] WARNING  C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\ ]8;id=10301074;file://C:\Users\savac\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=10301075;file://C:\Users\savac\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             .venv\Lib\site-packages\kedro\config\omegaconf_config.py:637:
                             UserWarning: register_new_resolver() is deprecated and will be
                             removed in a future release.
                             Use register_resolver() instead.
                             See https://github.com/hydra-ecosystem/omegaconf/issues/426 for
                             migration instructions.

                               OmegaConf.register_new_resolver(

                    WARNING  C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\ ]8;id=10301080;file://C:\Users\savac\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=10301081;file://C:\Users\savac\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             .venv\Lib\site-packages\kedro\config\omegaconf_config.py:644:
                             UserWarning: register_new_resolver() is deprecated and will be
                             removed in a future release.
                             Use register_resolver() instead.
                             See https://github.com/hydra-ecosystem/omegaconf/issues/426 for
                             migration instructions.

                               OmegaConf.register_new_resolver(

                    WARNING  C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\ ]8;id=10301086;file://C:\Users\savac\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=10301087;file://C:\Users\savac\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             .venv\Lib\site-packages\kedro\config\omegaconf_config.py:749:
                             UserWarning: register_new_resolver() is deprecated and will be
                             removed in a future release.
                             Use register_resolver() instead.
                             See https://github.com/hydra-ecosystem/omegaconf/issues/426 for
                             migration instructions.

                               OmegaConf.register_new_resolver("oc.env", oc.env)

                    INFO     No typed parameter requirements found, returning original   ]8;id=10301094;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\validation\parameter_validator.py\parameter_validator.py]8;;\:]8;id=10301095;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\validation\parameter_validator.py#124\124]8;;\
                             parameters

[10/19/26 16:47:58] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=10301102;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=10301103;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro_telemetry\plugin.py#279\279]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

                    INFO     Kedro project spaceflights                                             ]8;id=10301109;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=10301110;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py#227\227]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=10301116;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=10301117;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py#228\228]8;;\
                             'pipelines'

                    INFO     Registered line magic 'run_viz'                                        ]8;id=10301123;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=10301124;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py#234\234]8;;\

In [5]:
catalog

'companies': kedro_datasets.pandas.csv_dataset.CSVDataset
'reviews': kedro_datasets.pandas.csv_dataset.CSVDataset
'shuttles': kedro_datasets.pandas.excel_dataset.ExcelDataset
'preprocessed_companies': kedro_datasets.pandas.parquet_dataset.ParquetDataset
'preprocessed_shuttles': kedro_datasets.pandas.parquet_dataset.ParquetDataset
'parameters': kedro.io.memory_dataset.MemoryDataset(data='<dict>')

In [6]:
companies = catalog.load("companies")
companies.head()

                    INFO     Loading data from companies (CSVDataset)...                       ]8;id=10301131;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=10301132;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\io\data_catalog.py#1151\1151]8;;\

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100%,Isle of Man,1.0,f
1,46728,100%,NaN,1.0,f
2,34618,38%,Isle of Man,1.0,f
3,28619,100%,Bosnia and Herzegovina,1.0,f
4,8240,NaN,Chile,1.0,t

In [7]:
companies.dtypes

id                     int64
company_rating           str
company_location         str
total_fleet_count    float64
iata_approved            str
dtype: object

In [8]:
def is_true(x: pd.Series) -> pd.Series:
    return x == "t"

In [9]:
companies["iata_approved"] = is_true(companies["iata_approved"])

In [10]:
companies.head()

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100%,Isle of Man,1.0,False
1,46728,100%,NaN,1.0,False
2,34618,38%,Isle of Man,1.0,False
3,28619,100%,Bosnia and Herzegovina,1.0,False
4,8240,NaN,Chile,1.0,True

In [11]:
companies.dtypes

id                     int64
company_rating           str
company_location         str
total_fleet_count    float64
iata_approved           bool
dtype: object

In [12]:
def parse_percentage(x: pd.Series) -> pd.Series:
    return x.str.replace("%", "").astype(float)

In [13]:
companies["company_rating"] = parse_percentage(companies["company_rating"])

In [14]:
companies.head()

,id,company_rating,company_location,total_fleet_count,iata_approved
0,3888,100.0,Isle of Man,1.0,False
1,46728,100.0,NaN,1.0,False
2,34618,38.0,Isle of Man,1.0,False
3,28619,100.0,Bosnia and Herzegovina,1.0,False
4,8240,NaN,Chile,1.0,True

In [15]:
companies.dtypes

id                     int64
company_rating       float64
company_location         str
total_fleet_count    float64
iata_approved           bool
dtype: object

In [16]:
type(companies)

<class 'pandas.DataFrame'>

In [17]:
shuttles = catalog.load("shuttles")

                    INFO     Loading data from shuttles (ExcelDataset)...                      ]8;id=10301137;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=10301138;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\io\data_catalog.py#1151\1151]8;;\

In [18]:
shuttles.head()

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,f,f,"$1,715.0",32413
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,f,f,"$3,405.0",14122
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,t,f,"$1,806.0",47761
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,f,f,"$1,676.0",26648
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,f,f,"$4,718.0",26648

In [19]:
shuttles.dtypes

id                           int64
shuttle_location               str
shuttle_type                   str
engine_type                    str
engine_vendor                  str
engines                    float64
passenger_capacity           int64
cancellation_policy            str
crew                       float64
d_check_complete               str
moon_clearance_complete        str
price                          str
company_id                   int64
dtype: object

In [20]:
shuttles.iloc[: 5:]

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,f,f,"$1,715.0",32413
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,f,f,"$3,405.0",14122
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,t,f,"$1,806.0",47761
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,f,f,"$1,676.0",26648
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,f,f,"$4,718.0",26648

In [21]:
shuttles["d_check_complete"] = is_true(shuttles["d_check_complete"])
shuttles["moon_clearance_complete"] = is_true(shuttles["moon_clearance_complete"])

In [22]:
def parse_money(x: pd.Series) -> pd.Series:
    return x.str.replace("$","").str.replace(",","").astype(float)

In [23]:
shuttles["price"] = parse_money(shuttles["price"])

In [24]:
shuttles.dtypes

id                           int64
shuttle_location               str
shuttle_type                   str
engine_type                    str
engine_vendor                  str
engines                    float64
passenger_capacity           int64
cancellation_policy            str
crew                       float64
d_check_complete              bool
moon_clearance_complete       bool
price                      float64
company_id                   int64
dtype: object

In [29]:
shuttles.head()

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,moon_clearance_complete,price,company_id
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,False,1715.0,32413
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,False,3405.0,14122
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,False,1806.0,47761
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,False,1676.0,26648
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,False,4718.0,26648

In [26]:
reviews = catalog.load("reviews")

[10/19/26 16:48:00] INFO     Loading data from reviews (CSVDataset)...                         ]8;id=10301143;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=10301144;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\io\data_catalog.py#1151\1151]8;;\

In [30]:
reviews.head()

,shuttle_id,review_scores_rating,review_scores_comfort,review_scores_amenities,review_scores_trip,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month
0,45163,91.0,10.0,9.0,9.0,9.0,9.0,9.0,26,0.77
1,49438,96.0,10.0,10.0,10.0,10.0,10.0,9.0,61,0.62
2,10750,97.0,10.0,10.0,10.0,10.0,10.0,10.0,467,4.66
3,4146,95.0,10.0,10.0,10.0,10.0,9.0,9.0,318,3.22
4,5067,97.0,10.0,9.0,10.0,10.0,9.0,10.0,22,0.29

In [36]:
rated_shuttles = shuttles.merge(reviews, left_on="id", right_on="shuttle_id")
rated_shuttles.head()

,id,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,...,shuttle_id,review_scores_rating,review_scores_comfort,review_scores_amenities,review_scores_trip,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,...,45163,91.0,10.0,9.0,9.0,9.0,9.0,9.0,26,0.77
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,...,49438,96.0,10.0,10.0,10.0,10.0,10.0,9.0,61,0.62
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,...,10750,97.0,10.0,10.0,10.0,10.0,10.0,10.0,467,4.66
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,...,4146,95.0,10.0,10.0,10.0,10.0,9.0,9.0,318,3.22
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,...,5067,97.0,10.0,9.0,10.0,10.0,9.0,10.0,22,0.29

In [37]:
rated_shuttles.columns

Index(['id', 'shuttle_location', 'shuttle_type', 'engine_type',
       'engine_vendor', 'engines', 'passenger_capacity', 'cancellation_policy',
       'crew', 'd_check_complete', 'moon_clearance_complete', 'price',
       'company_id', 'shuttle_id', 'review_scores_rating',
       'review_scores_comfort', 'review_scores_amenities',
       'review_scores_trip', 'review_scores_crew', 'review_scores_location',
       'review_scores_price', 'number_of_reviews', 'reviews_per_month'],
      dtype='str')

In [41]:
model_input_table = rated_shuttles.merge(companies,left_on="company_id", right_on="id")
model_input_table.head()

,id_x,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,...,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month,id_y,company_rating,company_location,total_fleet_count,iata_approved
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,...,9.0,9.0,9.0,26,0.77,32413,100.0,Faroe Islands,1.0,False
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,...,10.0,10.0,9.0,61,0.62,14122,100.0,Malta,1.0,True
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,...,10.0,10.0,10.0,467,4.66,47761,100.0,Niue,2.0,False
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,...,10.0,9.0,9.0,318,3.22,26648,100.0,Niue,2.0,True
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,...,10.0,9.0,10.0,22,0.29,26648,100.0,Niue,2.0,True

In [42]:
model_input_table.dropna()

,id_x,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,...,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month,id_y,company_rating,company_location,total_fleet_count,iata_approved
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,...,9.0,9.0,9.0,26,0.77,32413,100.0,Faroe Islands,1.0,False
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,...,10.0,10.0,9.0,61,0.62,14122,100.0,Malta,1.0,True
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,...,10.0,10.0,10.0,467,4.66,47761,100.0,Niue,2.0,False
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,...,10.0,9.0,9.0,318,3.22,26648,100.0,Niue,2.0,True
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,...,10.0,9.0,10.0,22,0.29,26648,100.0,Niue,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15169,29334,Sao Tome and Principe,Type V7,Quantum,ThetaBase Services,1.0,3,flexible,1.0,True,...,10.0,8.0,10.0,2,2.00,46943,94.0,Peru,2.0,False
15183,49839,Rwanda,Type V5,Nuclear,"Banks, Wood and Phillips",1.0,1,flexible,1.0,True,...,10.0,10.0,10.0,2,2.00,2878,93.0,Bosnia and Herzegovina,3.0,True
15199,59798,Bouvet Island (Bouvetoya),Type V5,Plasma,ThetaBase Services,0.0,7,strict,4.0,True,...,10.0,10.0,10.0,3,3.00,8409,98.0,Maldives,9.0,False
15255,20330,Uzbekistan,Type V5,Quantum,ThetaBase Services,1.0,2,flexible,1.0,False,...,10.0,10.0,10.0,1,1.00,5701,100.0,Costa Rica,1.0,True
15265,16445,Nicaragua,Type V5,Plasma,ThetaBase Services,1.0,1,flexible,3.0,False,...,10.0,10.0,10.0,3,3.00,13728,100.0,Pakistan,1.0,False