In [10]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from scikit-learn) (2.5.4)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

In [8]:
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [36]:
%reload_kedro

[10/19/26 18:22:11] INFO     Resolved project path as:                                              ]8;id=12621696;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=12621697;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py#261\261]8;;\
                             C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\spac
                             eflights.
                             To set a different path, run '%reload_kedro <project_root>'

                    WARNING  C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\ ]8;id=12621702;file://C:\Users\savac\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=12621703;file://C:\Users\savac\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             .venv\Lib\site-packages\kedro\config\omegaconf_config.py:637:
                             UserWarning: register_new_resolver() is deprecated and will be
                             removed in a future release.
                             Use register_resolver() instead.
                             See https://github.com/hydra-ecosystem/omegaconf/issues/426 for
                             migration instructions.

                               OmegaConf.register_new_resolver(

                    WARNING  C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\ ]8;id=12621708;file://C:\Users\savac\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=12621709;file://C:\Users\savac\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             .venv\Lib\site-packages\kedro\config\omegaconf_config.py:644:
                             UserWarning: register_new_resolver() is deprecated and will be
                             removed in a future release.
                             Use register_resolver() instead.
                             See https://github.com/hydra-ecosystem/omegaconf/issues/426 for
                             migration instructions.

                               OmegaConf.register_new_resolver(

                    WARNING  C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\ ]8;id=12621714;file://C:\Users\savac\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=12621715;file://C:\Users\savac\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             .venv\Lib\site-packages\kedro\config\omegaconf_config.py:749:
                             UserWarning: register_new_resolver() is deprecated and will be
                             removed in a future release.
                             Use register_resolver() instead.
                             See https://github.com/hydra-ecosystem/omegaconf/issues/426 for
                             migration instructions.

                               OmegaConf.register_new_resolver("oc.env", oc.env)

                    INFO     No typed parameter requirements found, returning original   ]8;id=12621720;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\validation\parameter_validator.py\parameter_validator.py]8;;\:]8;id=12621721;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\validation\parameter_validator.py#124\124]8;;\
                             parameters

                    INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=12621726;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=12621727;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro_telemetry\plugin.py#279\279]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

[10/19/26 18:22:12] INFO     Kedro project spaceflights                                             ]8;id=12621732;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=12621733;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py#227\227]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=12621738;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=12621739;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py#228\228]8;;\
                             'pipelines'

                    INFO     Registered line magic 'run_viz'                                        ]8;id=12621744;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=12621745;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\ipython\__init__.py#234\234]8;;\

In [38]:
catalog.load("params:a")

[10/19/26 18:22:40] INFO     Loading data from params:a (MemoryDataset)...                     ]8;id=12621750;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=12621751;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\io\data_catalog.py#1151\1151]8;;\

1

In [11]:
df = catalog.load("model_input_table")
df.head()

[10/19/26 17:31:57] INFO     Loading data from model_input_table (ParquetDataset)...           ]8;id=12621690;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=12621691;file://C:\Users\savac\data-science-ml-portfolio\SpaceFlightKedroPipeline\.venv\Lib\site-packages\kedro\io\data_catalog.py#1151\1151]8;;\

,id_x,shuttle_location,shuttle_type,engine_type,engine_vendor,engines,passenger_capacity,cancellation_policy,crew,d_check_complete,...,review_scores_crew,review_scores_location,review_scores_price,number_of_reviews,reviews_per_month,id_y,company_rating,company_location,total_fleet_count,iata_approved
0,45163,Sao Tome and Principe,Type V5,Plasma,ThetaBase Services,2.0,4,moderate,2.0,False,...,9.0,9.0,9.0,26,0.77,32413,100.0,Faroe Islands,1.0,False
1,49438,Wallis and Futuna,Type V2,Plasma,ThetaBase Services,3.0,5,moderate,3.0,False,...,10.0,10.0,9.0,61,0.62,14122,100.0,Malta,1.0,True
2,10750,Niue,Type F5,Quantum,ThetaBase Services,1.0,2,strict,1.0,True,...,10.0,10.0,10.0,467,4.66,47761,100.0,Niue,2.0,False
3,4146,Malta,Type V2,Quantum,ThetaBase Services,1.0,2,moderate,1.0,False,...,10.0,9.0,9.0,318,3.22,26648,100.0,Niue,2.0,True
4,5067,Malta,Type V2,Plasma,ThetaBase Services,5.0,10,strict,5.0,False,...,10.0,9.0,10.0,22,0.29,26648,100.0,Niue,2.0,True

In [13]:
from sklearn.model_selection import train_test_split

In [17]:
features = [
    "engines",
    "passenger_capacity",
    "crew",
    "d_check_complete",
    "moon_clearance_complete",
    "iata_approved",
    "company_rating",
    "review_scores_rating",
]

In [19]:
X = df[features]
y = df["price"]

In [20]:
X.head()

,engines,passenger_capacity,crew,d_check_complete,moon_clearance_complete,iata_approved,company_rating,review_scores_rating
0,2.0,4,2.0,False,False,False,100.0,91.0
1,3.0,5,3.0,False,False,True,100.0,96.0
2,1.0,2,1.0,True,False,False,100.0,97.0
3,1.0,2,1.0,False,False,True,100.0,95.0
4,5.0,10,5.0,False,False,True,100.0,97.0

In [21]:
y.head()

0    1715.0
1    3405.0
2    1806.0
3    1676.0
4    4718.0
Name: price, dtype: float64

In [35]:
def split_data(df: pd.DataFrame, parameters: dict) -> tuple:
    X= df[parameters["features"]]
    y = df["price"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=parameters["test_size"])
    return X_train, X_test, y_train, y_test

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [27]:
len(X_train), len(X_test)

(4821, 1206)

In [28]:
len(y_train), len(y_test)

(4821, 1206)

In [29]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [30]:
model.predict(X_test)

array([1912.47401714, 1836.75417992, 1497.47680047, ..., 2489.44726327,
       1856.42181843, 1516.63678582], shape=(1206,))

In [31]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [33]:
y_predict = model.predict(X_test)
r2_score(y_test, y_predict)

0.3269873900834913